spring:
  profiles:
    active: dev

  application:
    name: proyecto-practica

  data:
    mongodb:
      uri: mongodb://localhost:27017/proyecto_practica
      auto-index-creation: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

server:
  port: 8080

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  level:
    root: INFO
    com.example.proyectopractica: DEBUG
    org.springframework.web: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /v3/api-docs
